# Generated by Django 4.2.18 on 2025-03-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=10)),
                ('coordinate', models.CharField(max_length=50)),
                ('temperature', models.CharField(max_length=20)),
                ('pressure', models.CharField(max_length=20)),
                ('humidity', models.CharField(max_length=20)),
                ('weather_main', models.CharField(max_length=50)),
                ('weather_description', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=20)),
            ],
        ),
    ]
